{
 "title": "UniTN_Digital_Twin",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Physical Twin: UL Bitrate",
   "type": "timeseries",
   "description": "Uplink bitrate",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "ul_bitrate", "legendFormat": "ue{{ue}}" }
   ]
  },
  {
   "title": "Physical Twin: DL Bitrate",
   "type": "timeseries",
   "description": "Downlink bitrate",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "dl_bitrate", "legendFormat": "ue{{ue}}" }
   ]
  },
  {
   "title": "Digital Twin: UPF UL Bitrate",
   "type": "timeseries",
   "description": "UPF Uplink bitrate",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    { "expr": "upf_ul_bitrate", "legendFormat": "{{interface}}" }
   ]
  },
  {
   "title": "Digital Twin: UPF DL Bitrate",
   "type": "timeseries",
   "description": "UPF Downlink bitrate",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    { "expr": "upf_dl_bitrate", "legendFormat": "{{interface}}" }
   ]
  }
 ]
}