scrape_configs:
  # Prometheus self-monitoring
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporters for UPFs
  - job_name: node-exporter
    static_configs:
      - targets:
        - "192.168.2.2:9100"  # upf_default
        - "192.168.2.2:9101"  # upf_internet
        - "192.168.2.2:9102"  # upf_ims
        - "192.168.2.2:9103"  # upf_sos

  # cAdvisor for container metrics
  - job_name: cadvisor
    static_configs:
      - targets: ["192.168.2.2:8080"]
